{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}

-- | Cloud-init configuration composition for VMs.
--
-- All host-side I/O (writing the @user-data@ / @meta-data@ /
-- @network-config@ files into the target directory and assembling
-- the NoCloud ISO via @genisoimage@ / @mkisofs@) lives on the
-- agent side now — see "Corvus.Node.CloudInit". This module
-- stays daemon-side because everything in it consults DB state
-- (SSH keys, hostnames, instance IDs) or operates on pure values.
module Corvus.CloudInit
  ( -- * Configuration
    CloudInitConfig (..)
  , defaultCloudInitConfig

    -- * ISO paths (purely computed; the directory is materialised by the agent, not the daemon)
  , getCloudInitDir

    -- * User-data / meta-data composition (pure)
  , renderUserData
  , generateMetaData
  , isRawUserDataScript

    -- * Auto-generated network-config (slice 10 — overlay IPAM)
  , StaticNicConfig (..)
  , generateStaticNetworkConfig
  )
where

import Corvus.Qemu.Config (QemuConfig, getEffectiveBasePath)
import Corvus.Utils.Yaml (yamlQQ)
import Data.Aeson (Value (..))
import qualified Data.Aeson.Key as Key
import qualified Data.Aeson.KeyMap as KM
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Vector as V
import qualified Data.Yaml as Yaml
import System.FilePath ((</>))

-- | Cloud-init configuration
data CloudInitConfig = CloudInitConfig
  { ciUser :: !Text
  -- ^ Username to create (used by default config)
  , ciHostname :: !Text
  -- ^ Hostname for the VM
  , ciInstanceId :: !Text
  -- ^ Instance ID (should be unique per VM)
  , ciCustomUserData :: !(Maybe Text)
  -- ^ Custom user-data YAML (replaces default generation when set)
  , ciNetworkConfig :: !(Maybe Text)
  -- ^ Network-config YAML (not generated by default)
  , ciInjectSshKeys :: !Bool
  -- ^ When True, inject DB SSH keys into custom userData
  }
  deriving (Show, Eq)

-- | Default cloud-init configuration
defaultCloudInitConfig :: CloudInitConfig
defaultCloudInitConfig =
  CloudInitConfig
    { ciUser = "corvus"
    , ciHostname = "corvus-vm"
    , ciInstanceId = "corvus-001"
    , ciCustomUserData = Nothing
    , ciNetworkConfig = Nothing
    , ciInjectSshKeys = True
    }

-- | Compute the directory the cloud-init artefacts for a VM live
-- under. Pure path arithmetic — no @mkdir@ is performed here; the
-- agent's 'Corvus.Node.CloudInit.assembleCloudInitIso' creates the
-- directory at ISO-assembly time.
getCloudInitDir :: QemuConfig -> Text -> IO FilePath
getCloudInitDir config vmName = do
  basePath <- getEffectiveBasePath config
  pure $ basePath </> T.unpack vmName

-- | Generate user-data YAML for cloud-init with multiple SSH keys
generateUserData :: CloudInitConfig -> [Text] -> Text
generateUserData config sshPubKeys' =
  let sshPubKeys = map T.strip sshPubKeys'
      user = ciUser config
      home = "/home/" <> user
      runcmds =
        [ "chmod 700 " <> home
        , "chmod 700 " <> home <> "/.ssh"
        , "chmod 600 " <> home <> "/.ssh/authorized_keys"
        , "chown -R " <> user <> ":" <> user <> " " <> home <> "/.ssh"
        , "echo 'permit nopass " <> user <> "' > /etc/doas.d/" <> user <> ".conf 2>/dev/null || true"
        , "rc-service sshd restart || systemctl restart ssh || systemctl restart sshd || true"
        ]
   in "#cloud-config\n"
        <> T.decodeUtf8
          ( Yaml.encode
              [yamlQQ|
            ssh_genkeytypes:
              - rsa
              - ed25519
            bootcmd:
              - test -f /etc/ssh/ssh_host_rsa_key || ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
              - test -f /etc/ssh/ssh_host_ed25519_key || ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
            chpasswd:
              expire: false
            users:
              - name: #{user}
                sudo: ALL=(ALL) NOPASSWD:ALL
                shell: /bin/sh
                lock_passwd: false
                plain_text_passwd: corvus
                ssh_authorized_keys: #{sshPubKeys}
            ssh_pwauth: true
            disable_root: true
            package_update: false
            package_upgrade: false
            runcmd: #{runcmds}
          |]
          )

-- | Is the supplied user-data a raw script (passthrough) rather than
-- structured YAML we should wrap with a @#cloud-config@ header?
--
-- Raw scripts are anything starting with @#@ after leading whitespace:
--
--   * @#!/bin/bash@ and friends
--   * @#cloud-config@ (already has its own header)
--   * @#ps1_sysnative@ (cloudbase-init on Windows)
--   * @#include@ (cloud-init include directive)
isRawUserDataScript :: Text -> Bool
isRawUserDataScript t = T.isPrefixOf "#" (T.stripStart t)

-- | Decide what to write as the @user-data@ file contents.
--
-- Four cases:
--
--   1. No 'ciCustomUserData' — generate the default cloud-config from
--      'generateUserData' using the VM's user/hostname/SSH keys.
--   2. Custom user-data that looks like a raw script (starts with
--      @#@ per 'isRawUserDataScript') — use it verbatim, no header
--      prepended. This is what Windows cloudbase-init scripts and
--      shebang scripts need.
--   3. Structured YAML with @ciInjectSshKeys@ and at least one key to
--      inject — inject the keys into the YAML, then prepend
--      @#cloud-config@.
--   4. Structured YAML otherwise — prepend @#cloud-config@ and use as-is.
renderUserData :: CloudInitConfig -> [Text] -> Text
renderUserData config sshPubKeys = case ciCustomUserData config of
  Just customData
    | isRawUserDataScript customData -> customData
    | ciInjectSshKeys config && not (null sshPubKeys) ->
        case injectSshKeysIntoYaml customData sshPubKeys of
          Right merged -> "#cloud-config\n" <> merged
          Left _ -> "#cloud-config\n" <> customData
    | otherwise -> "#cloud-config\n" <> customData
  Nothing -> generateUserData config sshPubKeys

-- | Generate meta-data text for cloud-init from the
-- 'CloudInitConfig'. Pure; the agent writes this verbatim into
-- @<targetDir>/meta-data@.
generateMetaData :: CloudInitConfig -> Text
generateMetaData config =
  T.decodeUtf8 $
    Yaml.encode
      [yamlQQ|
        instance-id: #{ciInstanceId config}
        local-hostname: #{ciHostname config}
      |]

-- | Per-NIC static configuration produced by the daemon's IPAM
-- for a NoCloud network-config v2 file. @prefix@ is the CIDR
-- prefix length; @gateway@ is the L3 gateway on the network's
-- owner node ("" to omit, e.g. for an L2-only segment).
data StaticNicConfig = StaticNicConfig
  { snicMac :: !Text
  , snicIp :: !Text
  , snicPrefix :: !Int
  , snicGateway :: !Text
  }
  deriving (Eq, Show)

-- | Build a cloud-init NoCloud @network-config@ (version 2 schema)
-- with one Ethernet stanza per NIC, matched by MAC. Returns
-- 'Nothing' for an empty input so callers can short-circuit and
-- leave the file unwritten.
--
-- DHCP still serves the same lease via the dnsmasq host
-- reservation; the static stanza is belt-and-braces for guests
-- without a DHCP client or with aggressive lease-cache eviction.
generateStaticNetworkConfig :: [StaticNicConfig] -> Maybe Text
generateStaticNetworkConfig [] = Nothing
generateStaticNetworkConfig nics =
  Just $ "version: 2\nethernets:\n" <> T.concat (zipWith renderNic [0 :: Int ..] nics)
  where
    renderNic ix nic =
      let key = "eth" <> T.pack (show ix)
          gwLine =
            if T.null (snicGateway nic)
              then ""
              else "    gateway4: " <> snicGateway nic <> "\n"
       in "  "
            <> key
            <> ":\n"
            <> "    match:\n"
            <> "      macaddress: "
            <> snicMac nic
            <> "\n"
            <> "    addresses:\n"
            <> "      - "
            <> snicIp nic
            <> "/"
            <> T.pack (show (snicPrefix nic))
            <> "\n"
            <> gwLine

--------------------------------------------------------------------------------
-- SSH key injection
--------------------------------------------------------------------------------

-- | Inject SSH public keys into a cloud-config YAML text.
-- Parses the YAML as a Value, merges keys into the first user's
-- @ssh_authorized_keys@ (or adds a top-level key), and re-serializes.
injectSshKeysIntoYaml :: Text -> [Text] -> Either Text Text
injectSshKeysIntoYaml yamlText sshPubKeys =
  case Yaml.decodeEither' (T.encodeUtf8 yamlText) :: Either Yaml.ParseException Value of
    Left err -> Left $ "Failed to parse custom user-data YAML: " <> T.pack (show err)
    Right val ->
      let merged = mergeKeysIntoValue val (map T.strip sshPubKeys)
       in Right $ T.decodeUtf8 $ Yaml.encode merged

-- | Merge SSH keys into a parsed cloud-config Value.
-- If 'users' array exists, inject into the first user's ssh_authorized_keys.
-- Otherwise, add a top-level ssh_authorized_keys key.
mergeKeysIntoValue :: Value -> [Text] -> Value
mergeKeysIntoValue (Object obj) keys =
  case KM.lookup (Key.fromText "users") obj of
    Just (Array users)
      | not (V.null users) ->
          let firstUser = V.head users
              updatedUser = injectKeysIntoUser firstUser keys
              updatedUsers = Array $ V.cons updatedUser (V.tail users)
           in Object $ KM.insert (Key.fromText "users") updatedUsers obj
    _ ->
      -- No users section: add top-level ssh_authorized_keys
      let keyList = Array $ V.fromList $ map (String . T.strip) keys
       in Object $ KM.insert (Key.fromText "ssh_authorized_keys") keyList obj
mergeKeysIntoValue val _ = val

-- | Inject SSH keys into a single user object's ssh_authorized_keys.
injectKeysIntoUser :: Value -> [Text] -> Value
injectKeysIntoUser (Object userObj) keys =
  let newKeys = map (String . T.strip) keys
      existingKeys = case KM.lookup (Key.fromText "ssh_authorized_keys") userObj of
        Just (Array arr) -> V.toList arr
        _ -> []
      mergedKeys = Array $ V.fromList $ existingKeys ++ newKeys
   in Object $ KM.insert (Key.fromText "ssh_authorized_keys") mergedKeys userObj
injectKeysIntoUser val _ = val
