{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}

-- | Cloud-init configuration generation for VMs.
-- Creates NoCloud datasource ISOs for injecting SSH keys and configuration.
module Corvus.CloudInit
  ( -- * Configuration
    CloudInitConfig (..)
  , defaultCloudInitConfig

    -- * ISO paths
  , getCloudInitIsoPath
  , getCloudInitDir

    -- * ISO generation
  , generateCloudInitIso
  , removeCloudInitIso

    -- * SSH key injection
  , injectSshKeysIntoYaml
  )
where

import Control.Exception (SomeException, try)
import Control.Monad (when)
import Corvus.Qemu.Config (QemuConfig, getEffectiveBasePath)
import Corvus.Utils.Yaml (yamlQQ)
import Data.Aeson (Value (..))
import qualified Data.Aeson.Key as Key
import qualified Data.Aeson.KeyMap as KM
import Data.Maybe (catMaybes)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.IO as TIO
import qualified Data.Vector as V
import qualified Data.Yaml as Yaml
import System.Directory (createDirectoryIfMissing, doesFileExist, removeFile)
import System.Exit (ExitCode (..))
import System.FilePath ((</>))
import System.Process (readProcessWithExitCode)

-- | Cloud-init configuration
data CloudInitConfig = CloudInitConfig
  { ciUser :: !Text
  -- ^ Username to create (used by default config)
  , ciHostname :: !Text
  -- ^ Hostname for the VM
  , ciInstanceId :: !Text
  -- ^ Instance ID (should be unique per VM)
  , ciCustomUserData :: !(Maybe Text)
  -- ^ Custom user-data YAML (replaces default generation when set)
  , ciNetworkConfig :: !(Maybe Text)
  -- ^ Network-config YAML (not generated by default)
  , ciInjectSshKeys :: !Bool
  -- ^ When True, inject DB SSH keys into custom userData
  }
  deriving (Show, Eq)

-- | Default cloud-init configuration
defaultCloudInitConfig :: CloudInitConfig
defaultCloudInitConfig =
  CloudInitConfig
    { ciUser = "corvus"
    , ciHostname = "corvus-vm"
    , ciInstanceId = "corvus-001"
    , ciCustomUserData = Nothing
    , ciNetworkConfig = Nothing
    , ciInjectSshKeys = True
    }

-- | Get the directory for storing cloud-init files for a VM
-- Returns: $qcBasePath/<vm-name>/
getCloudInitDir :: QemuConfig -> Text -> IO FilePath
getCloudInitDir config vmName = do
  basePath <- getEffectiveBasePath config
  let vmDir = basePath </> T.unpack vmName
  createDirectoryIfMissing True vmDir
  pure vmDir

-- | Get the path to the cloud-init ISO for a VM
-- Returns: $qcBasePath/<vm-name>/cloud-init.iso
getCloudInitIsoPath :: QemuConfig -> Text -> IO FilePath
getCloudInitIsoPath config vmName = do
  vmDir <- getCloudInitDir config vmName
  pure $ vmDir </> "cloud-init.iso"

-- | Generate user-data YAML for cloud-init with multiple SSH keys
generateUserData :: CloudInitConfig -> [Text] -> Text
generateUserData config sshPubKeys' =
  let sshPubKeys = map T.strip sshPubKeys'
      user = ciUser config
      home = "/home/" <> user
      runcmds =
        [ "chmod 700 " <> home
        , "chmod 700 " <> home <> "/.ssh"
        , "chmod 600 " <> home <> "/.ssh/authorized_keys"
        , "chown -R " <> user <> ":" <> user <> " " <> home <> "/.ssh"
        , "echo 'permit nopass " <> user <> "' > /etc/doas.d/" <> user <> ".conf 2>/dev/null || true"
        , "rc-service sshd restart || systemctl restart ssh || systemctl restart sshd || true"
        , "systemctl enable qemu-guest-agent || rc-update add qemu-guest-agent default || true"
        , "systemctl start qemu-guest-agent || rc-service qemu-guest-agent start || true"
        ]
   in "#cloud-config\n"
        <> T.decodeUtf8
          ( Yaml.encode
              [yamlQQ|
            ssh_genkeytypes:
              - rsa
              - ed25519
            bootcmd:
              - test -f /etc/ssh/ssh_host_rsa_key || ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
              - test -f /etc/ssh/ssh_host_ed25519_key || ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
            chpasswd:
              expire: false
            users:
              - name: #{user}
                sudo: ALL=(ALL) NOPASSWD:ALL
                shell: /bin/sh
                lock_passwd: false
                plain_text_passwd: corvus
                ssh_authorized_keys: #{sshPubKeys}
            ssh_pwauth: true
            disable_root: true
            package_update: true
            package_upgrade: false
            packages:
              - qemu-guest-agent
            runcmd: #{runcmds}
          |]
          )

-- | Generate meta-data for cloud-init
generateMetaData :: CloudInitConfig -> Text
generateMetaData config =
  T.decodeUtf8 $
    Yaml.encode
      [yamlQQ|
        instance-id: #{ciInstanceId config}
        local-hostname: #{ciHostname config}
      |]

-- | Generate a cloud-init NoCloud ISO image with multiple SSH keys.
-- The ISO contains user-data, meta-data, and optionally network-config files.
-- Returns the path to the generated ISO, or an error message.
generateCloudInitIso :: FilePath -> CloudInitConfig -> [Text] -> IO (Either Text FilePath)
generateCloudInitIso targetDir config sshPubKeys = do
  -- Ensure target directory exists
  createDirectoryIfMissing True targetDir

  let userDataPath = targetDir </> "user-data"
      metaDataPath = targetDir </> "meta-data"
      networkConfigPath = targetDir </> "network-config"
      isoPath = targetDir </> "cloud-init.iso"

  -- Generate user-data: custom or default.
  -- Raw scripts (starting with #, e.g. #ps1_sysnative, #!, #cloud-config)
  -- are used as-is. Structured YAML gets a #cloud-config header prepended.
  let isRawScript t = T.isPrefixOf "#" (T.stripStart t)
      userDataContent = case ciCustomUserData config of
        Just customData
          | isRawScript customData -> customData
          | ciInjectSshKeys config && not (null sshPubKeys) ->
              case injectSshKeysIntoYaml customData sshPubKeys of
                Right merged -> "#cloud-config\n" <> merged
                Left _ -> "#cloud-config\n" <> customData
          | otherwise -> "#cloud-config\n" <> customData
        Nothing -> generateUserData config sshPubKeys

  -- Write cloud-init files
  TIO.writeFile userDataPath userDataContent
  TIO.writeFile metaDataPath (generateMetaData config)

  -- Write optional network-config
  mNetworkConfigFile <- case ciNetworkConfig config of
    Just nc -> do
      TIO.writeFile networkConfigPath nc
      pure $ Just networkConfigPath
    Nothing -> pure Nothing

  let inputFiles = [userDataPath, metaDataPath] ++ catMaybes [mNetworkConfigFile]

  -- Try genisoimage first, fall back to mkisofs
  result <- tryGenIsoImage inputFiles isoPath
  case result of
    Right _ -> do
      -- Clean up temp files
      mapM_ removeIfExists inputFiles
      pure $ Right isoPath
    Left _ -> do
      -- Try mkisofs as fallback
      mkResult <- tryMkIsofs inputFiles isoPath
      case mkResult of
        Right _ -> do
          mapM_ removeIfExists inputFiles
          pure $ Right isoPath
        Left err -> pure $ Left err

-- | Try to create ISO using genisoimage
tryGenIsoImage :: [FilePath] -> FilePath -> IO (Either Text ())
tryGenIsoImage inputFiles isoPath = do
  result <-
    try $
      readProcessWithExitCode
        "genisoimage"
        (["-output", isoPath, "-volid", "cidata", "-joliet", "-rock"] ++ inputFiles)
        ""
  case result of
    Left (_ :: SomeException) -> pure $ Left "genisoimage not found"
    Right (ExitSuccess, _, _) -> pure $ Right ()
    Right (ExitFailure n, _, stderr) ->
      pure $
        Left $
          "genisoimage failed (exit " <> T.pack (show n) <> "): " <> T.pack stderr

-- | Try to create ISO using mkisofs
tryMkIsofs :: [FilePath] -> FilePath -> IO (Either Text ())
tryMkIsofs inputFiles isoPath = do
  result <-
    try $
      readProcessWithExitCode
        "mkisofs"
        (["-output", isoPath, "-volid", "cidata", "-joliet", "-rock"] ++ inputFiles)
        ""
  case result of
    Left (_ :: SomeException) -> pure $ Left "mkisofs not found"
    Right (ExitSuccess, _, _) -> pure $ Right ()
    Right (ExitFailure n, _, stderr) ->
      pure $
        Left $
          "mkisofs failed (exit " <> T.pack (show n) <> "): " <> T.pack stderr

-- | Remove cloud-init ISO file
removeCloudInitIso :: FilePath -> IO ()
removeCloudInitIso = removeIfExists

-- | Helper to remove file if it exists
removeIfExists :: FilePath -> IO ()
removeIfExists path = do
  exists <- doesFileExist path
  when exists $ removeFile path

--------------------------------------------------------------------------------
-- SSH key injection
--------------------------------------------------------------------------------

-- | Inject SSH public keys into a cloud-config YAML text.
-- Parses the YAML as a Value, merges keys into the first user's
-- @ssh_authorized_keys@ (or adds a top-level key), and re-serializes.
injectSshKeysIntoYaml :: Text -> [Text] -> Either Text Text
injectSshKeysIntoYaml yamlText sshPubKeys =
  case Yaml.decodeEither' (T.encodeUtf8 yamlText) :: Either Yaml.ParseException Value of
    Left err -> Left $ "Failed to parse custom user-data YAML: " <> T.pack (show err)
    Right val ->
      let merged = mergeKeysIntoValue val (map T.strip sshPubKeys)
       in Right $ T.decodeUtf8 $ Yaml.encode merged

-- | Merge SSH keys into a parsed cloud-config Value.
-- If 'users' array exists, inject into the first user's ssh_authorized_keys.
-- Otherwise, add a top-level ssh_authorized_keys key.
mergeKeysIntoValue :: Value -> [Text] -> Value
mergeKeysIntoValue (Object obj) keys =
  case KM.lookup (Key.fromText "users") obj of
    Just (Array users)
      | not (V.null users) ->
          let firstUser = V.head users
              updatedUser = injectKeysIntoUser firstUser keys
              updatedUsers = Array $ V.cons updatedUser (V.tail users)
           in Object $ KM.insert (Key.fromText "users") updatedUsers obj
    _ ->
      -- No users section: add top-level ssh_authorized_keys
      let keyList = Array $ V.fromList $ map (String . T.strip) keys
       in Object $ KM.insert (Key.fromText "ssh_authorized_keys") keyList obj
mergeKeysIntoValue val _ = val

-- | Inject SSH keys into a single user object's ssh_authorized_keys.
injectKeysIntoUser :: Value -> [Text] -> Value
injectKeysIntoUser (Object userObj) keys =
  let newKeys = map (String . T.strip) keys
      existingKeys = case KM.lookup (Key.fromText "ssh_authorized_keys") userObj of
        Just (Array arr) -> V.toList arr
        _ -> []
      mergedKeys = Array $ V.fromList $ existingKeys ++ newKeys
   in Object $ KM.insert (Key.fromText "ssh_authorized_keys") mergedKeys userObj
injectKeysIntoUser val _ = val
