"""Low-level shell helpers — SSH transports to nodes and VMs.

Most tests should drive a VM via its pycapnp `Client`. SSH is the
escape hatch for things the daemon can't observe of itself: kernel
sysctl state, filesystem layout, package versions, route tables, etc.

Two variants:

* `NodeShell` — single-leg, host→node SSH over VSOCK. Targets a CID
  the host can VSOCK-connect to directly, i.e. a top-level orchestrator
  Gentoo VM (a node in the harness's vocabulary).
* `VmShell` — two-leg tunnel for VMs created **inside** a node.
  AF_VSOCK CIDs are scoped per-hypervisor, so the host can't reach
  the vm directly; we chain a host→node SSH hop whose
  remote command is `socat - VSOCK-CONNECT:<vm_cid>:22`, and then
  run the VM-side SSH over that stream. OpenSSH's ControlMaster
  keeps the VM connection open across many `run()` calls, so only
  the first invocation pays the handshake.

Both rely on the integration-test images: they ship sshd plus a small
`socat VSOCK-LISTEN:22,fork,reuseaddr TCP:127.0.0.1:22` relay (Alpine)
or systemd's built-in VSOCK SSH socket activation (Gentoo). Both the
Gentoo node image and the Alpine VM image embed the public half of
`integration_tests/keys/corvus-test-key` into `corvus@`'s
authorized_keys at bake time, so one keypair authorises both legs of
the tunnel.
"""
from __future__ import annotations

import shlex
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


# Conventional location of the shared keypair, generated by
# `make test-image-key`. The pubkey is baked into both the Alpine
# VM image and the Gentoo node image; the private key on the host
# drives both legs of the SSH tunnel.
HOST_ALPINE_KEY_PATH = (
    Path(__file__).resolve().parent.parent / "keys" / "corvus-test-key"
)


@dataclass(frozen=True)
class NodeShell:
    """Single-leg VSOCK SSH to a node — i.e. one of the orchestrator
    Gentoo VMs that hosts an inner Corvus daemon."""

    cid: int
    user: str = "root"
    key_path: Optional[Path] = None
    port: int = 22

    def run(
        self,
        command: str,
        *,
        timeout_sec: float = 60.0,
        check: bool = True,
    ) -> subprocess.CompletedProcess:
        """Run `command` on the node via SSH over VSOCK. Returns
        the CompletedProcess (stdout/stderr captured)."""
        socat = shutil.which("socat")
        if not socat:
            raise RuntimeError("`socat` not on PATH; required for VSOCK SSH")
        ssh = shutil.which("ssh")
        if not ssh:
            raise RuntimeError("`ssh` not on PATH")
        argv = [
            ssh,
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "BatchMode=yes",
            "-o", f"ProxyCommand={socat} - VSOCK-CONNECT:{self.cid}:{self.port}",
        ]
        if self.key_path is not None:
            argv += ["-i", str(self.key_path)]
        argv += [f"{self.user}@vsock-{self.cid}", command]
        return subprocess.run(
            argv,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout_sec,
            check=check,
        )

    def read_file(self, path: str) -> str:
        out = self.run(f"cat {path}")
        return out.stdout.decode("utf-8", errors="replace")


@dataclass(frozen=True)
class SshResult:
    """One completed SSH invocation. `stdout`/`stderr` are best-effort
    UTF-8 decoded; non-UTF-8 bytes are replaced rather than raising."""

    exit_code: int
    stdout: str
    stderr: str


class VmShell:
    """SSH transport to a VM created by the inner daemon.

    Tunnel shape:

        host ssh
          ├─ -i KEY -o ControlMaster=auto -o ControlPath=… -o ControlPersist=300
          ├─ -o ProxyCommand=<VM_PROXY>
          └─ corvus@vsock-<vm_cid>  <command>

        VM_PROXY (spawned once per master):
          ssh -i KEY -o ProxyCommand="socat - VSOCK-CONNECT:<node_cid>:22"
              corvus@vsock-<node_cid>  'socat - VSOCK-CONNECT:<vm_cid>:22'

    The node-hop's remote command is `socat`, so its stdin/stdout
    becomes the transport stream for the VM-side SSH. ControlMaster
    on the *host* keeps the VM connection alive across many `run()`
    calls — only the first call spawns the ProxyCommand subprocess.
    Subsequent calls multiplex over the existing connection and cost
    only a sub-100ms round-trip.

    Must be `close()`d (or used as a context manager) so the
    ControlMaster is torn down and the vm-side sshd session ends
    promptly. Otherwise the connection lingers for up to
    ControlPersist seconds holding state on the vm's sshd and a
    stray socat on the node.
    """

    def __init__(
        self,
        *,
        node_cid: int,
        host_key_path: Path,
        vm_cid: Optional[int] = None,
        vm_tcp_port: Optional[int] = None,
        user: str = "corvus",
        node_user: str = "corvus",
        node_key_path: Optional[Path] = None,
        node_port: int = 22,
        vm_port: int = 22,
        control_dir: Optional[Path] = None,
    ) -> None:
        if not shutil.which("ssh"):
            raise RuntimeError("`ssh` not on PATH")
        if not shutil.which("socat"):
            raise RuntimeError("`socat` not on PATH; required for VSOCK SSH")
        if (vm_cid is None) == (vm_tcp_port is None):
            raise ValueError(
                "VmShell needs exactly one of `vm_cid` (VSOCK transport) "
                "or `vm_tcp_port` (node-side TCP hostfwd transport)"
            )
        self.node_cid = node_cid
        self.vm_cid = vm_cid
        self.vm_tcp_port = vm_tcp_port
        # SSH "hostname" label used for ControlPath cache + Permission
        # Denied messages. The actual transport is the ProxyCommand;
        # this just disambiguates concurrent shells.
        self._target_label = (
            f"vsock-{vm_cid}" if vm_cid is not None else f"tcp-{vm_tcp_port}"
        )
        self.host_key_path = Path(host_key_path)
        # The node-hop key may differ from the vm-leg key. For the
        # baked Alpine VSOCK tests they're the same (`HOST_ALPINE_KEY_PATH`,
        # baked into both the node and the Alpine vm at image-build
        # time). For cloud-init tests they MUST differ: the node still
        # only trusts the harness's baked key, while the vm trusts a
        # freshly generated per-VM key injected by cloud-init.
        self.node_key_path = Path(node_key_path or HOST_ALPINE_KEY_PATH)
        self.user = user
        self.node_user = node_user
        self.node_port = node_port
        self.vm_port = vm_port
        # Own a private tempdir for the control socket so concurrent
        # VmShells (e.g. xdist workers, multiple test classes) don't
        # collide. Keep the dirname short — OpenSSH's ControlPath has
        # a ~107 char limit on most platforms.
        self._owns_control_dir = control_dir is None
        self.control_dir = Path(
            control_dir or tempfile.mkdtemp(prefix="corvus-it-ssh-")
        )
        # Single control socket per VmShell instance, named by whichever
        # of the two transports we're using — keeps concurrent shells
        # over different transports from clobbering each other.
        socket_tag = (
            f"vm-{vm_cid}" if vm_cid is not None else f"tcp-{vm_tcp_port}"
        )
        self.control_path = self.control_dir / f"{socket_tag}.sock"
        self._closed = False

    # ---- public API --------------------------------------------------------

    def run(
        self,
        command: str,
        *,
        timeout_sec: float = 60.0,
        check: bool = True,
    ) -> SshResult:
        """Run a single shell command on the VM. Stdin is closed;
        stdout/stderr are captured in full and returned as strings.
        """
        argv = self._build_argv(command, connect_timeout=int(timeout_sec))
        proc = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout_sec + 5,
        )
        result = SshResult(
            exit_code=proc.returncode,
            stdout=proc.stdout.decode("utf-8", errors="replace"),
            stderr=proc.stderr.decode("utf-8", errors="replace"),
        )
        if check and result.exit_code != 0:
            raise RuntimeError(
                f"SSH command failed (exit {result.exit_code}): {command!r}\n"
                f"stderr: {result.stderr.strip()}"
            )
        return result

    def wait_ready(
        self,
        *,
        timeout_sec: float = 90.0,
        poll_sec: float = 2.0,
    ) -> None:
        """Poll `true` until SSH answers cleanly.

        Raises immediately on `Permission denied (publickey)` — that's
        a key/auth misconfiguration, not a transient "sshd still
        coming up" condition, and retrying would just blow the
        timeout for no benefit. All other failures are treated as
        transient (sshd not listening yet, VSOCK relay not started,
        VM still booting).
        """
        deadline = time.monotonic() + timeout_sec
        last_err = "no attempts yet"
        while True:
            try:
                result = self.run("true", timeout_sec=10.0, check=False)
            except subprocess.TimeoutExpired as e:
                last_err = f"timeout after {e.timeout}s"
            else:
                if result.exit_code == 0:
                    return
                err_lower = result.stderr.lower()
                if (
                    "permission denied" in err_lower
                    and "publickey" in err_lower
                ):
                    raise RuntimeError(
                        f"SSH key {self.host_key_path} rejected by VM "
                        f"({self._target_label}): {result.stderr.strip()}"
                    )
                last_err = (
                    f"exit {result.exit_code}; "
                    f"stderr: {result.stderr.strip() or '<empty>'}"
                )
            if time.monotonic() >= deadline:
                raise TimeoutError(
                    f"VM SSH ({self._target_label}) not ready after "
                    f"{timeout_sec}s; last error: {last_err}"
                )
            time.sleep(poll_sec)

    def close(self) -> None:
        """Tear down the ControlMaster and clean up the control dir."""
        if self._closed:
            return
        self._closed = True
        # Best-effort: ask the master to exit. If it never started
        # (e.g. wait_ready raised), this just no-ops.
        try:
            subprocess.run(
                [
                    "ssh",
                    "-O", "exit",
                    "-o", f"ControlPath={self.control_path}",
                    f"{self.user}@{self._target_label}",
                ],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=10,
            )
        except Exception:
            pass
        if self._owns_control_dir:
            shutil.rmtree(self.control_dir, ignore_errors=True)

    def __enter__(self) -> "VmShell":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    # ---- internals ---------------------------------------------------------

    @property
    def _vm_proxy_command(self) -> str:
        """ProxyCommand for the VM-side SSH: a shell-quoted SSH-to-node
        invocation whose remote command runs either
        `socat - VSOCK-CONNECT:<vm_cid>:22` (VSOCK transport) or
        `socat - TCP:127.0.0.1:<vm_tcp_port>` (node-side hostfwd
        transport). The node-hop SSH's stdin/stdout becomes the
        transport stream for the VM SSH.
        """
        node_proxy = (
            f"socat - VSOCK-CONNECT:{self.node_cid}:{self.node_port}"
        )
        if self.vm_tcp_port is not None:
            inner = f"socat - TCP:127.0.0.1:{self.vm_tcp_port}"
        else:
            inner = f"socat - VSOCK-CONNECT:{self.vm_cid}:{self.vm_port}"
        node_argv = [
            "ssh",
            "-i", str(self.node_key_path),
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "BatchMode=yes",
            "-o", f"ProxyCommand={node_proxy}",
            f"{self.node_user}@vsock-{self.node_cid}",
            inner,
        ]
        return shlex.join(node_argv)

    def _build_argv(
        self,
        command: Optional[str],
        *,
        connect_timeout: int,
    ) -> list[str]:
        argv = [
            "ssh",
            "-i", str(self.host_key_path),
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "BatchMode=yes",
            "-o", f"ConnectTimeout={max(connect_timeout, 5)}",
            "-o", "ControlMaster=auto",
            "-o", f"ControlPath={self.control_path}",
            "-o", "ControlPersist=300",
            "-o", f"ProxyCommand={self._vm_proxy_command}",
            f"{self.user}@{self._target_label}",
        ]
        if command is not None:
            argv.append(command)
        return argv
