"""Type stubs for the native _corvus extension module."""
from typing import Any, Union

def call(request: bytes) -> bytes: ...
def open(transport: bytes) -> Union[Any, bytes]:
    """Returns a PyCapsule on success, JSON error bytes on failure."""
def call_open(capsule: Any, request: bytes) -> bytes: ...
def close(capsule: Any) -> None: ...
def _shutdown() -> None: ...
