-- | Compatibility façade for the nodeagent VM session handlers.
module Corvus.Node.Caps.Session.Vm
  ( handleVmStart
  , doVmStart
  , handleVmStopGraceful
  , handleVmStopHard
  , handleVmPause
  , handleVmResume
  , handleVmSave
  , handleDeleteSavedState
  , handleDeleteTpmState
  , handleVmGuestExec
  , handleVmGuestExecStream
  , handleVmStatus
  , handleVmSetSpiceTicket
  , spawnVirtiofsdHelper
  , spawnSwtpmHelper
  , spawnSwtpmHelperSafe
  , reapEntryGracefully
  , reapSwtpmEntryGracefully
  , reapSpawnedHelpers
  , reapVmHelpers
  , respawnAfterExit
  , reapEntryAfterQuit
  , pollOutgoingMigrate
  , qmpMigrateWithConnectGrace
  , outgoingMigrateTimeoutSec
  , decodeVmSpec
  , decodeVmDriveSpec
  , decodeVmNetIfSpec
  , decodeVmSharedDirSpec
  , decodeVmGuestExecReq
  , encodeVmRuntimeInfo
  , encodeVmStopResult
  , encodeVmAgentStatus
  , encodeVmGuestExecInfo
  , agentQemuConfig
  , vfsBinary
  , waitForFirstQgaPing
  , forwardPipeToLog
  , captureStderrTail
  , stderrTailCapacity
  , pollForExit
  )
where

import Corvus.Node.Caps.Session.Utils
  ( agentQemuConfig
  , captureStderrTail
  , forwardPipeToLog
  , pollForExit
  , stderrTailCapacity
  , vfsBinary
  , waitForFirstQgaPing
  )
import Corvus.Node.Caps.Session.Vm.Access
import Corvus.Node.Caps.Session.Vm.Lifecycle
import Corvus.Node.Caps.Session.Vm.Process
import Corvus.Node.Caps.Session.Vm.Start
