"""End-to-end coverage for the ``corvus-web`` observability surface.

The doc at [doc/observability.md](../../doc/observability.md) promises
two things to operators: a Prometheus ``/metrics`` endpoint that
emits per-VM and per-node counters, and per-VM live-stats endpoints
at ``/api/vms/<id>/stats/{history,ws}``. Until now none of that was
tested end-to-end — a refactor that broke a counter name, dropped a
label, stopped emitting the ``corvus_vm_up`` gauge, or wedged the
WebSocket dispatch would only surface after a Prometheus scrape
failed in production.

This file:

* Spawns ``corvus-web`` on the host via the
  :class:`WebGateway` harness piece, pointing at the inner daemon's
  TCP relay with the same mTLS cert dir the pycapnp client uses.
* Boots one Alpine VM and exercises every observability surface
  the doc enumerates in a single test method (one boot amortises
  the ~30 s VM startup across all assertions, matching the pattern
  in :mod:`test_serial_console`).

What's covered:

* ``GET /metrics`` returns 503 during cold start, then 200 after the
  poller's first iteration completes (~10 s).
* The exposition contains every counter family from the doc.
* Counters cleared as monotonic (CPU seconds, disk-write bytes)
  strictly increase after a guest workload + one poller tick.
* ``GET /api/vms/<id>/stats/history`` returns a non-empty list,
  capped at 60 samples, oldest-first.
* The ``/api/vms/<id>/stats/ws`` WebSocket pushes live samples at
  the agent's ~10 s cadence; the test collects ≥ 2 frames and
  asserts the timestamp advances.

What's NOT covered here:

* The "VM gone from /metrics after STALE_SECONDS" path. metrics.py
  doesn't emit ``corvus_vm_up == 0`` for stopped VMs — they vanish
  from the exposition after 60 s of no fresh samples. A test for
  that path would just sit on a 60-second sleep; left as a future
  add if the staleness window changes.
* Node-level counters under stress. The node gauges (``load1``,
  ``memory_*``, ``storage_*``) are asserted as present but the
  values are whatever the host happens to report; pinning specific
  thresholds would be flaky.
* The SPICE-over-WS and serial-over-WS bridges (Bucket 2's scope).
"""

from __future__ import annotations

import json
import time

from corvus_test_harness import SingleNodeCase, VmSsh, WebGateway
from websockets.sync.client import connect as ws_connect


def _poll_until(cond, *, timeout_sec: float, msg: str, poll_sec: float = 0.5) -> None:
    deadline = time.monotonic() + timeout_sec
    while time.monotonic() < deadline:
        if cond():
            return
        time.sleep(poll_sec)
    raise AssertionError(f"{msg} (waited {timeout_sec}s)")


def _parse_metric_line(line: str) -> tuple[str, dict[str, str], float] | None:
    """Parse one Prometheus exposition-format line into
    ``(name, labels, value)``. Returns None for comments / blanks.

    Example: ``corvus_vm_up{vm_id="3",vm_name="x",node="n"} 1.0``
    → ``("corvus_vm_up", {"vm_id": "3", "vm_name": "x", "node": "n"}, 1.0)``.

    Doesn't try to be a full parser — labels with embedded commas or
    quotes aren't generated by prometheus_client for our label keys
    (all our labels are simple strings), so a naive split is enough.
    """
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    # Find the metric name (everything up to '{' or whitespace).
    if "{" in line:
        name_end = line.index("{")
        name = line[:name_end]
        labels_end = line.index("}", name_end)
        labels_str = line[name_end + 1 : labels_end]
        rest = line[labels_end + 1 :].strip()
    else:
        # No labels — split on first whitespace.
        parts = line.split(None, 1)
        name = parts[0]
        labels_str = ""
        rest = parts[1] if len(parts) > 1 else ""
    labels: dict[str, str] = {}
    if labels_str:
        for kv in labels_str.split(","):
            k, _, v = kv.partition("=")
            labels[k.strip()] = v.strip().strip('"')
    # value is the first token of `rest`
    value_str = rest.split()[0] if rest else "0"
    return (name, labels, float(value_str))


def _find_metric(
    body: str,
    name: str,
    label_filter: dict[str, str] | None = None,
) -> list[tuple[dict[str, str], float]]:
    """Return ``[(labels, value), …]`` for every series named ``name``
    that matches ``label_filter`` (subset match)."""
    out: list[tuple[dict[str, str], float]] = []
    for line in body.splitlines():
        parsed = _parse_metric_line(line)
        if parsed is None:
            continue
        n, labels, value = parsed
        if n != name:
            continue
        if label_filter and not all(
            labels.get(k) == v for k, v in label_filter.items()
        ):
            continue
        out.append((labels, value))
    return out


class TestObservability(SingleNodeCase):
    """One VM, one corvus-web spawn, every documented endpoint."""

    def test_metrics_and_stats_end_to_end(self):
        """Boot VM → /metrics → drive workload → re-scrape → /stats/history
        → /stats/ws. Single boot, sequential phases."""

        # User-mode NIC so the agent's per-tap counters appear in the
        # nets list (a no-NIC VM would still pass the counter-name
        # checks via labels-missing, but it's a less informative
        # assertion). See test_vm_lifecycle.py for the same pattern.
        class _ObsVm(VmSsh):
            def _net_ifs(self):
                return [{"type": "user"}]

        with _ObsVm(self) as vm:
            vm_id = vm.cap.show().id
            vm_name = vm.cap.show().name

            # ── Phase A: wait until the daemon has at least one real
            # stats sample. VmSsh's wait_for_qga returns after the
            # first QGA ping; the StatusPoller's first sample lands a
            # few seconds later. metrics.py:162-165 skips zero-sampled
            # VMs, so corvus-web's poller would otherwise warm up
            # with an empty per-VM cache and the first /metrics
            # scrape wouldn't list our VM.
            _poll_until(
                lambda: (
                    vm.cap.show().stats is not None
                    and vm.cap.show().stats.sampled_at_nanos > 0
                ),
                timeout_sec=30.0,
                msg="daemon never reported a non-zero stats sample for VM",
            )

            # ── Phase B: spawn corvus-web on the host pointing at the
            # inner daemon. ``warning`` log level keeps the test
            # output clean; bump to ``debug`` when diagnosing.
            with WebGateway(self.node) as web:
                # The /metrics poller wakes every 10 s; allow 30 s
                # so a single missed iteration doesn't flake.
                web.wait_for_metrics_warmup(timeout_sec=30.0)
                body = web.get("/metrics")

                # ── Phase C: every counter family from
                # doc/observability.md is present in the exposition.
                # We check presence by name (HELP/TYPE lines suffice
                # for that) plus one per-series sample on
                # corvus_vm_up to confirm the VM-labelled series
                # actually carries our vm_id.
                vm_metric_families = [
                    "corvus_vm_up",
                    "corvus_vm_cpu_seconds_total",
                    "corvus_vm_memory_rss_bytes",
                    "corvus_vm_memory_balloon_actual_bytes",
                    "corvus_vm_memory_balloon_max_bytes",
                    "corvus_vm_disk_read_bytes_total",
                    "corvus_vm_disk_write_bytes_total",
                    "corvus_vm_disk_read_ops_total",
                    "corvus_vm_disk_write_ops_total",
                    "corvus_vm_net_rx_bytes_total",
                    "corvus_vm_net_tx_bytes_total",
                ]
                node_metric_families = [
                    "corvus_node_load1",
                    "corvus_node_memory_total_bytes",
                    "corvus_node_memory_free_bytes",
                    "corvus_node_storage_total_bytes",
                    "corvus_node_storage_free_bytes",
                ]
                missing = [
                    name
                    for name in vm_metric_families + node_metric_families
                    if f"# HELP {name} " not in body
                ]
                assert not missing, (
                    f"metric families missing from /metrics exposition: {missing}\n"
                    f"body head:\n{body[:800]!r}"
                )

                # corvus_vm_up for our VM must be exactly 1.
                up_series = _find_metric(
                    body, "corvus_vm_up", {"vm_id": str(vm_id), "vm_name": vm_name}
                )
                assert up_series, (
                    f"no corvus_vm_up series for vm_id={vm_id} vm_name={vm_name!r}; "
                    f"body head:\n{body[:800]!r}"
                )
                assert up_series[0][1] == 1.0, (
                    f"corvus_vm_up for our VM expected 1.0, got {up_series[0][1]}"
                )

                # RSS must be > 0 (QEMU is alive and occupying RAM).
                rss = _find_metric(
                    body,
                    "corvus_vm_memory_rss_bytes",
                    {"vm_id": str(vm_id)},
                )
                assert rss and rss[0][1] > 0, f"rss not positive: {rss!r}"

                # ── Phase D: snapshot counters before workload, run a
                # CPU+disk-bound command in the guest, sleep one
                # poller tick + buffer, re-scrape, assert the
                # monotonic counters advanced.
                cpu_before = _find_metric(
                    body, "corvus_vm_cpu_seconds_total", {"vm_id": str(vm_id)}
                )[0][1]
                # Drive disk writes via QGA. 50 MB of zeros + fsync
                # keeps the test deterministic on tmpfs-backed
                # rootfs (no compression on the qcow2 hot path).
                r = vm.cap.guest_exec(
                    "/bin/sh -c 'dd if=/dev/urandom of=/tmp/load bs=1M count=50 "
                    "conv=fsync 2>/dev/null && sync'"
                )
                assert r.exit_code == 0, r

                # Two poller cycles + a small buffer: corvus-web's
                # poller is on a 10 s cadence and the daemon's
                # StatusPoller is independently on its own 10 s
                # cadence, so the cleanest "definitely picked up" wait
                # is one of each plus a buffer.
                time.sleep(22.0)

                body2 = web.get("/metrics")
                cpu_after = _find_metric(
                    body2, "corvus_vm_cpu_seconds_total", {"vm_id": str(vm_id)}
                )[0][1]
                assert cpu_after > cpu_before, (
                    f"cpu_seconds_total did not advance: "
                    f"before={cpu_before}, after={cpu_after}"
                )

                # At least one drive's write counter must be > 0
                # after the dd. We don't assume the drive *name* —
                # the test attaches one virtio drive, which the
                # agent reports under whatever blockdev id QEMU
                # assigns it.
                disk_writes_after = _find_metric(
                    body2,
                    "corvus_vm_disk_write_bytes_total",
                    {"vm_id": str(vm_id)},
                )
                assert disk_writes_after, "no disk write counter for our vm"
                assert any(v > 0 for _, v in disk_writes_after), (
                    f"all disk_write_bytes_total values are zero after dd; "
                    f"series: {disk_writes_after!r}"
                )

                # ── Phase E: REST stats history. The endpoint
                # returns a list of samples (oldest first, capped at
                # 60). After ~30 s of uptime + workload there's at
                # least one sample.
                history_text = web.get(f"/api/vms/{vm_id}/stats/history")
                history = json.loads(history_text)
                assert isinstance(history, list), f"expected list, got {type(history)}"
                assert history, "stats/history returned empty list"
                assert len(history) <= 60, (
                    f"stats/history returned more than 60 samples: {len(history)}"
                )
                latest = history[-1]
                assert latest["sampled_at_nanos"] > 0
                assert latest["host_rss_bytes"] > 0
                # Operator-facing claim from the docstring at
                # python/corvus_web/routes/vms.py:588-595 is
                # "oldest first". In practice two samples can land
                # within a sub-ms of each other at boot (the agent
                # snapshots once on starting → running, and the
                # StatusPoller's first periodic tick fires shortly
                # after) and end up index-swapped in the ring. We
                # assert the macro property — first < last — which
                # is what an operator reading a chart cares about.
                first_ts = history[0]["sampled_at_nanos"]
                last_ts = latest["sampled_at_nanos"]
                if len(history) > 1:
                    assert last_ts > first_ts, (
                        f"history end ({last_ts}) not after start ({first_ts}); "
                        f"all timestamps: {[s['sampled_at_nanos'] for s in history]!r}"
                    )

                # ── Phase F: live WebSocket stream. Collect 2
                # frames (the agent pushes every ~10 s, so 25 s
                # comfortably covers two pushes plus initial
                # subscription latency).
                frames: list[dict] = []
                with ws_connect(
                    web.ws_url(f"/api/vms/{vm_id}/stats/ws"),
                    open_timeout=10.0,
                ) as wsk:
                    deadline = time.monotonic() + 25.0
                    while len(frames) < 2 and time.monotonic() < deadline:
                        remaining = max(deadline - time.monotonic(), 0.1)
                        try:
                            msg = wsk.recv(timeout=remaining)
                        except TimeoutError:
                            break
                        frames.append(json.loads(msg))
                assert len(frames) >= 2, (
                    f"received {len(frames)} WS frames in 25 s; expected ≥ 2 "
                    f"(StatusPoller cadence is 10 s)"
                )
                # Each frame is a VmStats dict with the same shape
                # /history returns. Timestamps must be monotonic.
                ws_ts = [f["sampled_at_nanos"] for f in frames]
                assert ws_ts == sorted(ws_ts), (
                    f"WS frames not in timestamp order: {ws_ts!r}"
                )
                assert all(f["host_rss_bytes"] > 0 for f in frames), (
                    f"WS frame had zero host_rss_bytes: {frames!r}"
                )

    def test_metrics_503_during_cold_start(self):
        """Boot a fresh corvus-web with no VMs in the daemon yet, hit
        ``/metrics`` immediately, and assert the documented 503-with-
        ``warmed_up=False`` behaviour (see
        ``python/corvus_web/routes/metrics.py:190-195``).

        Smaller test: no VM boot needed. Useful to catch a refactor
        that drops the warmup gate and starts emitting
        empty-but-200 responses, which would silently
        zero out Prometheus alerts.
        """
        with WebGateway(self.node) as web:
            # Race the poller's first iteration. The
            # ``wait_for_metrics_warmup`` helper is the opposite of
            # what we want here — we explicitly do NOT wait for the
            # cache to warm up. Hit /metrics immediately.
            try:
                with web.get_response("/metrics", timeout_sec=2.0) as resp:
                    status = resp.status
                    body = resp.read().decode("utf-8")
            except Exception as e:
                # If the very first scrape raises (e.g. urllib
                # surfaces a 503 as HTTPError), that's still
                # consistent with the documented behaviour.
                from urllib.error import HTTPError

                if isinstance(e, HTTPError) and e.code == 503:
                    return
                raise
            # We expect 503; tolerate 200 only if the body indicates
            # the cache was already warmed (the poller can complete
            # one cycle inside the corvus-web startup window if the
            # daemon is fast).
            if status == 503:
                assert "not yet warmed up" in body, (
                    f"503 body should explain warmup: {body!r}"
                )
            else:
                assert status == 200, f"unexpected status {status}"
                # Cache warmed during startup — fine, just sanity-
                # check the body shape.
                assert "# HELP" in body or "# TYPE" in body, (
                    f"200 with no exposition: {body!r}"
                )
